### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by karmakaragradwip02** [NirAharon/BoT-SORT#117]
# I am trying in my custom dataset for a project.
### All the 60 epochs are running but after that this error is coming.
```bash
The full Error:
Traceback (most recent call last):
  File "fast_reid/tools/train_net.py", line 60, in <module>
    args=(args,),
  File "/mnt/DATA/EE22M204/BoT-SORT-main/fast_reid/fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "fast_reid/tools/train_net.py", line 47, in main
    return trainer.train()
  File "/mnt/DATA/EE22M204/BoT-SORT-main/fast_reid/fastreid/engine/defaults.py", line 350, in train
    super().train(self.start_epoch, self.max_epoch, self.iters_per_epoch)
  File "/mnt/DATA/EE22M204/BoT-SORT-main/fast_reid/fastreid/engine/train_loop.py", line 156, in train
    self.after_train()
  File "/mnt/DATA/EE22M204/BoT-SORT-main/fast_reid/fastreid/engine/train_loop.py", line 165, in after_train
    h.after_train()
  File "/mnt/DATA/EE22M204/BoT-SORT-main/fast_reid/fastreid/engine/hooks.py", line 383, in after_train
    self._do_eval()
  File "/mnt/DATA/EE22M204/BoT-SORT-main/fast_reid/fastreid/engine/hooks.py", line 351, in _do_eval
    results = self._func()
  File "/mnt/DATA/EE22M204/BoT-SORT-main/fast_reid/fastreid/engine/defaults.py", line 305, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/mnt/DATA/EE22M204/BoT-SORT-main/fast_reid/fastreid/engine/defaults.py", line 441, in test
    results_i = inference_on_dataset(model, data_loader, evaluator, flip_test=cfg.TEST.FLIP.ENABLED)
  File "/mnt/DATA/EE22M204/BoT-SORT-main/fast_reid/fastreid/evaluation/evaluator.py", line 156, in inference_on_dataset
    results = evaluator.evaluate()
  File "/mnt/DATA/EE22M204/BoT-SORT-main/fast_reid/fastreid/evaluation/reid_evaluation.py", line 107, in evaluate
    cmc, all_AP, all_INP = evaluate_rank(dist, query_pids, gallery_pids, query_camids, gallery_camids)
  File "/mnt/DATA/EE22M204/BoT-SORT-main/fast_reid/fastreid/evaluation/rank.py", line 198, in evaluate_rank
    return evaluate_cy(distmat, q_pids, g_pids, q_camids, g_camids, max_rank, use_metric_cuhk03)
  File "rank_cy.pyx", line 20, in rank_cy.evaluate_cy
  File "rank_cy.pyx", line 28, in rank_cy.evaluate_cy
  File "rank_cy.pyx", line 240, in rank_cy.eval_market1501_cy
AssertionError: Error: all query identities do not appear in gallery
```

All the steps are being followed.
```bash
python3 fast_reid/datasets/generate_mot_patches.py --data_path <dataets_dir> --mot 17
python3 fast_reid/tools/train_net.py --config-file ./fast_reid/configs/MOT17/sbs_S50.yml MODEL.DEVICE "cuda:0"
```

**Comment by karmakaragradwip02** [comment]
## Is their any folder or files that we have to change to run in our dataset.
### Meaning I am using the MOT17 format and I have changed the GMC files of MOT17 to my dataset GMC files for evaluation, Now are there any files that we have to change.

**Comment by karmakaragradwip02** [comment]
![Screenshot from 2024-10-02 11-01-04](https://github.com/user-attachments/assets/b9611209-4ba8-407c-8093-13876259a59d)
My ## BoT-SORT-main/fast_reid/datasets/MOT17-ReID
folder looks like the above images .

The path given for the query and the gallery are this path only.
What is the procedure and the structure for adding the folders and give the specific images.

**Comment by liusir466** [comment]
May I ask if you have solved the problem? I have also encountered this issue

**Comment by karmakaragradwip02** [comment]
No, I haven't solved the problem yet.

**Comment by liusir466** [comment]
So you're not continuing with it? Have you tried another data set?

**Comment by karmakaragradwip02** [comment]
Have you solved the problem(Training error) yet?
yes i am continuing with it.
i am also using DEEPOCSORT for my own data

**Comment by AleksanderB31** [comment]
Hi, was the problem resolved?
