### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by SimonCL17** [NirAharon/BoT-SORT#73]
Hi there, 

I have installed the repo and have tried running the following command:

python3 tools/mc_demo_yolov7.py --weights pretrained/yolov7-d6.pt --source ~/Videos/TrainStation.mp4 --fuse-score --agnostic-nms --with-reid

This has left me with the following error:

Traceback (most recent call last):
  File "/home/simon/Documents/Tracking/BoT-SORT/yolov7/utils/google_utils.py", line 27, in attempt_download
    assets = [x['name'] for x in response['assets']]  # release assets
KeyError: 'assets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/mc_demo_yolov7.py", line 254, in <module>
    detect()
  File "tools/mc_demo_yolov7.py", line 55, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/home/simon/Documents/Tracking/BoT-SORT/yolov7/models/experimental.py", line 241, in attempt_load
    attempt_download(w)
  File "/home/simon/Documents/Tracking/BoT-SORT/yolov7/utils/google_utils.py", line 31, in attempt_download
    tag = subprocess.check_output('git tag', shell=True).decode().split()[-1]

Please can you advise, am I doing something wrong?

Thanks,

Simon

**Comment by BoscoShin** [comment]
i have same problem in experiment with yolov7...

Does anyone know how to solve it

**Comment by sonodaatom** [comment]
This issue should be relevant

https://github.com/WongKinYiu/yolov7/issues/940
