### ISSUE TITLE
Error: all query identities do not appear in gallery

### ISSUE THREAD

**Issue by keeper-jie** [NirAharon/BoT-SORT#83]
I have tried to train some epoch and error occur. My mistake message like below and how to solve it:  
```
make: Leaving directory '/media/data1/project/BoT-SORT-main/fast_reid/fastreid/evaluation/rank_cylib'
Traceback (most recent call last):
  File "fast_reid/tools/train_net.py", line 60, in <module>
    args=(args,),
  File "/media/data1/project/BoT-SORT-main/fast_reid/fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "fast_reid/tools/train_net.py", line 47, in main
    return trainer.train()
  File "/media/data1/project/BoT-SORT-main/fast_reid/fastreid/engine/defaults.py", line 350, in train
    super().train(self.start_epoch, self.max_epoch, self.iters_per_epoch)
  File "/media/data1/project/BoT-SORT-main/fast_reid/fastreid/engine/train_loop.py", line 156, in train
    self.after_train()
  File "/media/data1/project/BoT-SORT-main/fast_reid/fastreid/engine/train_loop.py", line 165, in after_train
    h.after_train()
  File "/media/data1/project/BoT-SORT-main/fast_reid/fastreid/engine/hooks.py", line 383, in after_train
    self._do_eval()
  File "/media/data1/project/BoT-SORT-main/fast_reid/fastreid/engine/hooks.py", line 351, in _do_eval
    results = self._func()
  File "/media/data1/project/BoT-SORT-main/fast_reid/fastreid/engine/defaults.py", line 305, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/media/data1/project/BoT-SORT-main/fast_reid/fastreid/engine/defaults.py", line 441, in test
    results_i = inference_on_dataset(model, data_loader, evaluator, flip_test=cfg.TEST.FLIP.ENABLED)
  File "/media/data1/project/BoT-SORT-main/fast_reid/fastreid/evaluation/evaluator.py", line 156, in inference_on_dataset
    results = evaluator.evaluate()
  File "/media/data1/project/BoT-SORT-main/fast_reid/fastreid/evaluation/reid_evaluation.py", line 107, in evaluate
    cmc, all_AP, all_INP = evaluate_rank(dist, query_pids, gallery_pids, query_camids, gallery_camids)
  File "/media/data1/project/BoT-SORT-main/fast_reid/fastreid/evaluation/rank.py", line 198, in evaluate_rank
    return evaluate_cy(distmat, q_pids, g_pids, q_camids, g_camids, max_rank, use_metric_cuhk03)
  File "rank_cy.pyx", line 20, in rank_cy.evaluate_cy
  File "rank_cy.pyx", line 28, in rank_cy.evaluate_cy
  File "rank_cy.pyx", line 240, in rank_cy.eval_market1501_cy
AssertionError: Error: all query identities do not appear in gallery
```

**Comment by bosslv** [comment]
do you solve this problem? i have met the same

**Comment by shirtism** [comment]
I met the same problem,did you solve it?

**Comment by liusir466** [comment]
> I met the same problem,did you solve it?

did you solve it now？

**Comment by liusir466** [comment]
> did you solve it now？

did you solve it now？

**Comment by liusir466** [comment]
> I have tried to train some epoch and error occur. My mistake message like below and how to solve it:
> 
> ```
> make: Leaving directory '/media/data1/project/BoT-SORT-main/fast_reid/fastreid/evaluation/rank_cylib'
> Traceback (most recent call last):
>   File "fast_reid/tools/train_net.py", line 60, in <module>
>     args=(args,),
>   File "/media/data1/project/BoT-SORT-main/fast_reid/fastreid/engine/launch.py", line 71, in launch
>     main_func(*args)
>   File "fast_reid/tools/train_net.py", line 47, in main
>     return trainer.train()
>   File "/media/data1/project/BoT-SORT-main/fast_reid/fastreid/engine/defaults.py", line 350, in train
>     super().train(self.start_epoch, self.max_epoch, self.iters_per_epoch)
>   File "/media/data1/project/BoT-SORT-main/fast_reid/fastreid/engine/train_loop.py", line 156, in train
>     self.after_train()
>   File "/media/data1/project/BoT-SORT-main/fast_reid/fastreid/engine/train_loop.py", line 165, in after_train
>     h.after_train()
>   File "/media/data1/project/BoT-SORT-main/fast_reid/fastreid/engine/hooks.py", line 383, in after_train
>     self._do_eval()
>   File "/media/data1/project/BoT-SORT-main/fast_reid/fastreid/engine/hooks.py", line 351, in _do_eval
>     results = self._func()
>   File "/media/data1/project/BoT-SORT-main/fast_reid/fastreid/engine/defaults.py", line 305, in test_and_save_results
>     self._last_eval_results = self.test(self.cfg, self.model)
>   File "/media/data1/project/BoT-SORT-main/fast_reid/fastreid/engine/defaults.py", line 441, in test
>     results_i = inference_on_dataset(model, data_loader, evaluator, flip_test=cfg.TEST.FLIP.ENABLED)
>   File "/media/data1/project/BoT-SORT-main/fast_reid/fastreid/evaluation/evaluator.py", line 156, in inference_on_dataset
>     results = evaluator.evaluate()
>   File "/media/data1/project/BoT-SORT-main/fast_reid/fastreid/evaluation/reid_evaluation.py", line 107, in evaluate
>     cmc, all_AP, all_INP = evaluate_rank(dist, query_pids, gallery_pids, query_camids, gallery_camids)
>   File "/media/data1/project/BoT-SORT-main/fast_reid/fastreid/evaluation/rank.py", line 198, in evaluate_rank
>     return evaluate_cy(distmat, q_pids, g_pids, q_camids, g_camids, max_rank, use_metric_cuhk03)
>   File "rank_cy.pyx", line 20, in rank_cy.evaluate_cy
>   File "rank_cy.pyx", line 28, in rank_cy.evaluate_cy
>   File "rank_cy.pyx", line 240, in rank_cy.eval_market1501_cy
> AssertionError: Error: all query identities do not appear in gallery
> ```

did you solve it now？
